spring:
  datasource:
    dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
    url: jdbc:postgresql://localhost/clarin
    username: chrono
    password: chr0n0pre55
    initialize: false
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
      naming_strategy: org.hibernate.cfg.DefaultNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: validate
        temp:
          use_jdbc_metadata_defaults: false
        default_schema: koper
  application:
    name: ChronoPress
logging:
  level:
    org:
      hibernate: INFO
      spring: INFO
server:
  port: 8888
geolocation: http://maps.clarin-pl.eu/
upload: /opt/chronopress/upload/